### ISSUE TITLE
Run demo_planner.py error:  No contact sensors added to the prim: '/World/envs/env_0/Robot'.

### ISSUE THREAD

**Issue by Acrocorinth** [yang-zj1026/VLN-CE-Isaac#2]
![image](https://github.com/user-attachments/assets/817019aa-34c4-4f6c-a612-7a43b0372b94)

I followed the README and successfully installed it, but when running  demo_planner.py, I got the above error. What could be the reason?

**Comment by hujch23** [comment]
I encountered the same issue as well. May I ask how it was resolved?"

**Comment by leo7611** [comment]
Maybe you havn't got the robot usd asset ready yet

> I encountered the same issue as well. May I ask how it was resolved?"

**Comment by markinruc** [comment]
@leo7611 @Acrocorinth  Hi, I encountered the same issue. How to set the right robot usd asset? 

ValueError: No contact sensors added to the prim: '/World/envs/env_0/Robot'. This means that no rigid bodies are present under this prim. Please check the prim path.
